### ISSUE TITLE
[bug] Cannot read properties of undefined (reading 'src')

### ISSUE THREAD

**Issue by permlap** [silvia-odwyer/lightbox.js#18]
I'm trying to show different sets of image the first button contains 2 images and the second have only one image. Somehow, when I trigger the first button that contains  2 images and later trigger the second button, it throws Cannot read properties of undefined (reading 'src')

```
import { SlideshowLightbox, initLightboxJS } from "lightbox.js-react";
import React, { useEffect, useState } from "react";
import "lightbox.js-react/dist/index.css";
import Image from "next/image";
function Index() {
  const [images, setImages] = useState();
  useEffect(() => {
    initLightboxJS(process.env.LightboxJs_KEY, "individual");
  }, []);

  const user1 = [
    {
      src: "https://source.unsplash.com/sQZ_A17cufs/549x711",
      alt: "Mechanical keyboard with white keycaps.",
    },
    {
      src: "https://source.unsplash.com/sQZ_A17cufs/549x711",
      alt: "Mechanical keyboard with white keycaps.",
    },
  ];
  const user2 = [
    {
      src: "https://source.unsplash.com/rsAeSMzOX9Y/768x512",
      alt: "Mechanical keyboard with white, pastel green and red keycaps.",
    },
  ];
  const user3 = [
    {
      src: "https://source.unsplash.com/Z6SXt1v5tP8/768x512",
      alt: "Mechanical keyboard with white, pastel pink, yellow and red keycaps.",
    },
  ];

  const handleClick = (user) => {
    setImages(() => {
      return user.map((list) => {
        return { ...list };
      });
    });
  };
  return (
    <div>
      <button onClick={() => handleClick(user1)}>button1</button>
      <button onClick={() => handleClick(user2)}>button2</button>
      <button onClick={() => handleClick(user3)}>button3</button>
      {images ? (
        <SlideshowLightbox
          lightboxIdentifier="lightbox1"
          framework="next"
          images={images}
        >
          {images.map((image) => {
            return (
              <Image
                src={image.src}
                alt={image.alt}
                height={500}
                width={500}
                data-lightboxjs="lightbox1"
                quality={80}
              />
            );
          })}
        </SlideshowLightbox>
      ) : (
        <div>pick user</div>
      )}
    </div>
  );
}

export default Index;
```

**Comment by silvia-odwyer** [comment]
@permlap Thanks for letting me know about this bug, I've just released a new version of the library which should fix the issue. If you uninstall your current version of Lightbox.js and re-install the latest version, the issue should be fixed. If not, just let me know, thanks! ✅

**Comment by permlap** [comment]
It is still not working and throw the same error
here is my package.json

```
 "react": "18.2.0",
 "next": "^12.2.5",
"lightbox.js-react": "^0.6.3",
```

**Comment by silvia-odwyer** [comment]
@permlap I've just released a new version of the library which should fix the bug. It was working for React, but the bug was occurring in Next.js specifically, so I've fixed that issue for Next.js.
Let me know if it resolves the issue, thanks!

**Comment by permlap** [comment]
@silvia-odwyer  everything is working well thanks!
