### ISSUE TITLE
Is it possible to right click save image?

### ISSUE THREAD

**Issue by Maskoe** [silvia-odwyer/lightbox.js#4]
Hi,
pretty much see title.
I have people wanting to save the image via right click in full screen mode, but it wants to save the html instead.

I noticed you can right click "save Image as" on the little preview at the bottom, but users don't find that.

**Comment by silvia-odwyer** [comment]
@Maskoe Hi Mirco! That's an excellent point about saving images. Unfortunately the image zoom library I'm using doesn't support saving images via right click, but I could implement a workaround for this, outlined below.
 
I could add a download icon in the controls menu, which users could click on to save the image. Would that work? Or would you prefer to right click the image instead? Do let me know, as I'd love to implement an image saving feature. Thanks! 😄

**Comment by silvia-odwyer** [comment]
@Maskoe Hi Mirco, 
I've just released a new version of the library, which now has this functionality implemented.
You can enable the image download feature by setting the `downloadImages`  prop to true:
```jsx
<SlideshowLightbox downloadImages={true}>
    ...       
</SlideshowLightbox> 
```
Then you'll see the download button in the top-right controls. When the icon is clicked, the image is saved to the user's device.

![Imgur](https://i.imgur.com/eruKURL.png)

If you'd like me to place the icon anywhere else, do let me know that being said. 
Hopefully this helps solve the issue, and let me know if you have any queries etc, thanks! 😄

**Comment by silvia-odwyer** [comment]
@Maskoe Thanks for letting me know about this, if you were setting original and high-resolution images as referenced in Issue #1, the download button now saves the original, high-resolution image. This update is now available as a new release of the library on NPM.

However, if the issue still occurs, could you show me your <SlideshowLightbox> code, as well as a sample image array if you're passing an image array to the lightbox? It would help me with debugging and to reproduce the issue. Thanks very much! 😄

**Comment by Maskoe** [comment]
Here is a small sample to reproduce the issue. It still happens for me.

```
import { NextPage } from "next";
import Image from "next/image";
import { SlideshowLightbox } from "lightbox.js-react";

const Eyo: NextPage = (props) => {
  const imageLinks = [
    "https://revieweracc.blob.core.windows.net/images/8fd34edb-b9da-410f-83a8-a61285e2a7a7.jpg",
    "https://revieweracc.blob.core.windows.net/images/48c0462c-f03e-4a5a-bd74-36e203155fe6.jpg",
    "https://revieweracc.blob.core.windows.net/images/d99544e9-d65c-4001-b3e3-16b1bc00f00a.jpg",
  ];

  return (
    <>
      <SlideshowLightbox
        fullScreen={true}
        showThumbnails="true"
        className="container flex gap-2"
        theme="lightbox"
        lightboxIdentifier="lightbox"
        framework="next"
        images={imageLinks.map((link) => ({
          src: link,
          alt: "",
        }))}
      >
        {imageLinks.map((image) => (
          <Image
            key={image}
            className="shadow-xl rounded-lg"
            src={image}
            alt=""
            height={0}
            width={180}
            data-lightboxjs="lightbox"
          />
        ))}
      </SlideshowLightbox>
    </>
  );
};

export default Eyo;
```

**Comment by silvia-odwyer** [comment]
@Maskoe Hi Mirco, 
Thanks for the code sample! I've found the bug (related to image downloads for the Next.js version) and just implemented a fix for this. It's now available on NPM. Just be sure to add `downloadImages={true}` to the `SlideshowLightbox` component to include the download button also.

Let me know if this solves the issue for you, thanks Mirco! 😄

**Comment by Maskoe** [comment]
Hi
I dont know if this is a browser thing, but it just opens the image in a new tab now instead of downloading it.
This works well enough for me though. Users can just right click save on the new tab.

For me this is solved.

**Comment by silvia-odwyer** [comment]
@Maskoe Yes, the image is displayed in a new tab if the server hosting the images doesn't have CORS enabled. Otherwise the image is downloaded directly.

The only way to fix this would be to enable CORS on the server providing the images. So unfortunately I can't fix this on my end, but I'm glad the current implementation still works for you! 

Thanks again for the feature request, and if you have any other requests for new features in the future, be sure to let me know. Thanks, Mirco! 😄

**Comment by TimKraemer** [comment]
Is this download button still available? The docs don't say anything about it - also it does not seem to work anymore...

I'd very much appreciate this button - or alternatively a way for me to implement my own custom buttons into the menu...

```jsx
<SlideshowLightbox
      lightboxIdentifier="lightbox"
      downloadImage
      framework="next"
      images={images}
      className="container mx-auto !mt-4 grid grid-cols-3 gap-2"
      showThumbnails
      theme="lightbox"
    >
```
