### ISSUE TITLE
Images being cut off by caption

### ISSUE THREAD

**Issue by dandc11** [silvia-odwyer/lightbox.js#50]
Hi @silvia-odwyer, 

I'm running into an issue with my images being cut off when captions are used. The overlay for the caption covers the bottom part of the image, and the images themselves are perhaps not ideally sized within the lightbox. There may be an existing way to deal with this, but I'm not able to determine from the documentation about the props. Please see below:
![image](https://github.com/silvia-odwyer/lightbox.js/assets/34725981/a3087af0-ab17-48ca-864b-540fca49fcfd)

The CSS classes passed to `lightboxImgClass` are applied, but I'm finding it difficult to control the placement of the image through that because 

1. there are inline styles controlling the width and height of the image (see the screenshot below)
2. I can't get the style object I pass to `captionStyle` to take any effect (not sure what the expected syntax should be there, but I've tried numerous things)

![image](https://github.com/silvia-odwyer/lightbox.js/assets/34725981/16776f62-1c73-47ee-b47b-82faa0d3a627)
Ideally, I would like a way to keep my images in the center of the screen, keep them at no more than 80% of the viewport height, and have my captions display below. The captions would then not need to be foregrounded on an opaque overlay atop the image, but would alway show up below. Please let me know if there's a way to accomplish this. Thanks!

**Comment by silvia-odwyer** [comment]
@dandc11 Hi Dan! Thanks for letting me know about this issue, it's much appreciated. I've just updated the image sizing when captions are displayed. 

Could you update your version of the library to see if it fixes the issue? If not, just let me know and I'll take a look. Thanks!

**Comment by dandc11** [comment]
Hi @silvia-odwyer, I've made the update, and every page I've checked looks great so far. I think this solves our problem. Thank you once again!

**Comment by dandc11** [comment]
Actually, I have noticed a side effect of these changes on mobile. The `77vh` inline style applied to the `img` element is causing a distortion of the aspect-ratio. See here. 
![image](https://github.com/silvia-odwyer/lightbox.js/assets/34725981/1d10b424-0076-469d-9e90-89f1ab612148)

Briefly looking in Chrome's dev tools, I see that above `42em` there is a style of `object-fit: contain` being applied that prevents this. I would suggest either adding `object-fit: contain` below `42em` as well, or removing the inline style of `height: 77vh` below that same width.

**Comment by silvia-odwyer** [comment]
@dandc11 Hi Dan,
I've just updated the library to include the `object-fit: contain` style for images on mobile devices. Hopefully that rectifies the issue, but let me know if not, thanks!

**Comment by silvia-odwyer** [comment]
@dandc11 I've updated the library in my demo web app, and the style rule has been applied. The image uses the `object-fit: contain` style rule when displayed in mobile devices. Could you check if the style rule shown below has been added, and if there is any CSS rule which overrides it perhaps? 
![image-mh(3)](https://github.com/silvia-odwyer/lightbox.js/assets/32362757/4260fe8f-c3fa-4b83-9c27-78745724c906)

If the issue still persists, I'm just wondering if you could provide a code snippet that replicates the issue?

**Comment by dandc11** [comment]
Hi @silvia-odwyer, 

Hmm. Not sure why, but after reinstalling again to `1.0.4`, I still don't see that style property anywhere on mobile. It's not being overridden for me. It's certainly something I can add in my own stylesheet, but I'm not sure why it's not showing up. 
![image](https://github.com/silvia-odwyer/lightbox.js/assets/34725981/081f7ec7-1dec-4094-8256-913bcc79d478)

Here's a snippet of how I'm using the component: 
```javascript
    <SlideshowLightbox
      className={cx({
        [`grid ${gridColumns[cols]} place-items-center gap-2`]: showImageGrid,
        className,
      })}
      framework={useNextImage ? 'next' : ''}
      fullScreen={true}
      iconColor="white"
      images={imgObjArray}
      imgAnimation="fade"
      leftArrowClassname={'text-white text-2xl'}
      lightboxIdentifier={lightboxIdentifier}
      lightboxImgClass={lightboxImgClass}
      modalClose="clickOutside"
      onClose={onCloseCallback ? onCloseCallback : ''}
      onOpen={onOpenCallback ? onOpenCallback : ''}
      open={open}
      rightArrowClassname={'text-white text-2xl'}
      showControls={true}
      slideshowInterval={3500}
      startingSlideIndex={startingSlideIndex}
      theme="lightbox"
      thumbnailBorder="silver"
    >
      {children}
    </SlideshowLightbox>
```

**Comment by silvia-odwyer** [comment]
@dandc11 Hi Dan,
Thanks for providing the snippet, I've identified what was causing the issue. The classname wasn't being applied when `fullScreen` was set to `true`. I've just updated the library so that this is solved. Hopefully this rectifies the issue, and let me know if you have any queries.

**Comment by jnorris-cencal** [comment]
I updated to the new version but am still having the issue: <img class="imageModal undefined

**Comment by dandc11** [comment]
@silvia-odwyer , yep, it's fixed now. Thanks!

@jnorris-cencal , I think that's a different issue. I see a class of undefined on the `img` element as well, but I'm not sure what it was intended to be. Nevertheless, it doesn't affect this issue.

**Comment by jnorris-cencal** [comment]
@dandc11 Oops my bad, thanks for pointing that out :)

**Comment by dandc11** [comment]
@silvia-odwyer , one thing I have noticed, which I'm not sure is related to the fixes for this issue or not, is that lightbox images are no longer thumb-swipeable on mobile. The thumbnail list is swipeable, but I'm having to use the arrow buttons to proceed through the images. I confirmed on my iPhones 13 and 14, in Safari and Chrome.

**Comment by silvia-odwyer** [comment]
@jnorris-cencal I'll update the library to fix the classname error you mentioned. Also, if you have any bugs to report or if the lightbox isn't working as intended, just open an issue and I'll take a look. ✅

**Comment by silvia-odwyer** [comment]
@dandc11 I've just updated the library to fix this. Previously, if the `imgAnimation` prop was set to the `fade` option, the images could only be navigated via the arrows. Only the default option was swipeable, where the images moved from left-to-right. 

However, now if you swipe on desktop/mobile, the images will update accordingly. If you would prefer that the image is set to `fade` on desktop, but the images are animated when swiping on mobile, just let me know and I can add that feature.

**Comment by dandc11** [comment]
@silvia-odwyer , this is resolved and working well for me now. Many thanks!
